// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import PlaylistRefreshPollingController from "./playlist_refresh_polling_controller"
import ProgressPollingController from "./progress_polling_controller"

application.register("hello", HelloController)
application.register("playlist-refresh-polling", PlaylistRefreshPollingController)
application.register("progress-polling", ProgressPollingController)
