// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AdminAssociationSelectController from "./admin_association_select_controller"
import AdminActionProgressController from "./admin_action_progress_controller"
import AdminActionConfirmController from "./admin_action_confirm_controller"
import AdminClickableRowController from "./admin_clickable_row_controller"
import AdminClipboardController from "./admin_clipboard_controller"
import AdminInfiniteScrollController from "./admin_infinite_scroll_controller"
import AdminOriginalSongAlbumController from "./admin_original_song_album_controller"
import AdminOriginalSongPickerController from "./admin_original_song_picker_controller"
import AdminThemeController from "./admin_theme_controller"
import CountdownController from "./countdown_controller"
import HelloController from "./hello_controller"
import PlaylistRefreshPollingController from "./playlist_refresh_polling_controller"
import ProgressPollingController from "./progress_polling_controller"

application.register("admin-association-select", AdminAssociationSelectController)
application.register("admin-action-progress", AdminActionProgressController)
application.register("admin-action-confirm", AdminActionConfirmController)
application.register("admin-clickable-row", AdminClickableRowController)
application.register("admin-clipboard", AdminClipboardController)
application.register("admin-infinite-scroll", AdminInfiniteScrollController)
application.register("admin-original-song-album", AdminOriginalSongAlbumController)
application.register("admin-original-song-picker", AdminOriginalSongPickerController)
application.register("admin-theme", AdminThemeController)
application.register("countdown", CountdownController)
application.register("hello", HelloController)
application.register("playlist-refresh-polling", PlaylistRefreshPollingController)
application.register("progress-polling", ProgressPollingController)
