inherit_from:
  - .rubocop_base.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - tmp/**/*
    - .git/**/*

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - development
    - production
    - test

Rails/EnvironmentVariableAccess:
  AllowReads: true

Lint/MissingSuper:
  Enabled: true
  Exclude:
    - lib/redis_pool.rb
