inherit_from:
  - .rubocop_base.yml

plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - bin/*
    - db/schema.rb
    - vendor/**/*
    - tmp/**/*
    - .git/**/*
    - 'node_modules/**/*'

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/Pluck:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - development
    - production
    - test

Rails/EnvironmentVariableAccess:
  AllowReads: true

Lint/MissingSuper:
  Enabled: true
  Exclude:
    - lib/redis_pool.rb

Metrics/ClassLength:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: true
  Exclude:
    - app/avo/actions/*.rb

Style/SignalException:
  Enabled: true
  Exclude:
    - app/avo/actions/*.rb

Style/OpenStructUse:
  Enabled: true
  Exclude:
    - lib/apple_music/response.rb

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/*active_storage*'
