# frozen_string_literal: true

require 'test_helper'

module YtMusic
  class VideoTest < ActiveSupport::TestCase
    test 'parses YouTube player metadata dates' do
      video = Video.new(
        'videoDetails' => {
          'videoId' => 'pEzma7k8yDg',
          'title' => 'Chasing Rain',
          'channelId' => 'UCV2MrrTUCD449ieQpKaLK2A',
          'author' => 'DiGiTAL WiNG - Topic',
          'viewCount' => '1193',
          'shortDescription' => "Provided to YouTube by Rightsscale\n\nReleased on: 2026-05-04\n\nAuto-generated by YouTube."
        },
        'microformat' => {
          'playerMicroformatRenderer' => {
            'publishDate' => '2026-05-03T04:19:48-07:00',
            'uploadDate' => '2026-05-03T04:19:48-07:00'
          }
        }
      )

      assert_equal 'pEzma7k8yDg', video.video_id
      assert_equal 'Chasing Rain', video.title
      assert_equal 'DiGiTAL WiNG - Topic', video.channel_name
      assert_equal 1193, video.view_count
      assert_equal Date.new(2026, 5, 3), video.publish_date
      assert_equal Date.new(2026, 5, 3), video.upload_date
      assert_equal Date.new(2026, 5, 4), video.release_date
    end
  end
end
