# frozen_string_literal: true

require 'test_helper'

module YtMusic
  class VideoTest < ActiveSupport::TestCase
    test 'parses YouTube player metadata dates' do
      video = Video.new(
        'videoDetails' => {
          'videoId' => 'pEzma7k8yDg',
          'title' => 'Chasing Rain',
          'channelId' => 'UCV2MrrTUCD449ieQpKaLK2A',
          'author' => 'DiGiTAL WiNG - Topic',
          'viewCount' => '1193',
          'shortDescription' => "Provided to YouTube by Rightsscale\n\nReleased on: 2026-05-04\n\nAuto-generated by YouTube."
        },
        'microformat' => {
          'playerMicroformatRenderer' => {
            'publishDate' => '2026-05-03T04:19:48-07:00',
            'uploadDate' => '2026-05-03T04:19:48-07:00'
          }
        }
      )

      assert_equal 'pEzma7k8yDg', video.video_id
      assert_equal 'Chasing Rain', video.title
      assert_equal 'DiGiTAL WiNG - Topic', video.channel_name
      assert_equal 1193, video.view_count
      assert_equal Date.new(2026, 5, 3), video.publish_date
      assert_equal Date.new(2026, 5, 3), video.upload_date
      assert_equal Date.new(2026, 5, 4), video.release_date
    end

    test 'detects an art track from "Provided to YouTube by <配信代行社名>"' do
      video = Video.new(
        'videoDetails' => {
          'shortDescription' => "Provided to YouTube by Rightsscale\n\nReleased on: 2026-05-04\n\nAuto-generated by YouTube."
        },
        'microformat' => { 'playerMicroformatRenderer' => {} }
      )

      assert_equal 'Rightsscale', video.provided_by
      assert_predicate video, :art_track?
    end

    test 'is not an art track for a circle-uploaded music video without a "Provided to YouTube by" line' do
      video = Video.new(
        'videoDetails' => {
          'shortDescription' => "新譜のミュージックビデオです。\n\n東方同人音楽流通のアルバムに収録されています。"
        },
        'microformat' => { 'playerMicroformatRenderer' => {} }
      )

      assert_nil video.provided_by
      assert_not video.art_track?
      assert_nil video.release_date
    end

    test 'does not raise and returns nil fields when the description is missing' do
      video = Video.new(
        'videoDetails' => {},
        'microformat' => { 'playerMicroformatRenderer' => {} }
      )

      assert_nil video.provided_by
      assert_not video.art_track?
      assert_nil video.release_date
    end

    test 'does not raise and returns nil fields when the description is an empty string' do
      video = Video.new(
        'videoDetails' => { 'shortDescription' => '' },
        'microformat' => { 'playerMicroformatRenderer' => {} }
      )

      assert_nil video.provided_by
      assert_not video.art_track?
      assert_nil video.release_date
    end

    test 'metadata returns the full subset of fields used to persist video_metadata' do
      video = Video.new(
        'videoDetails' => {
          'videoId' => 'pEzma7k8yDg',
          'title' => 'Chasing Rain',
          'channelId' => 'UCV2MrrTUCD449ieQpKaLK2A',
          'author' => 'DiGiTAL WiNG - Topic',
          'viewCount' => '1193',
          'lengthSeconds' => '245',
          'shortDescription' => "Provided to YouTube by Rightsscale\n\nReleased on: 2026-05-04\n\nAuto-generated by YouTube."
        },
        'microformat' => {
          'playerMicroformatRenderer' => {
            'publishDate' => '2026-05-03T04:19:48-07:00',
            'uploadDate' => '2026-05-03T04:19:48-07:00',
            'category' => 'Music'
          }
        }
      )

      assert_equal(
        {
          video_id: 'pEzma7k8yDg',
          title: 'Chasing Rain',
          channel_id: 'UCV2MrrTUCD449ieQpKaLK2A',
          channel_name: 'DiGiTAL WiNG - Topic',
          view_count: 1193,
          publish_date: '2026-05-03',
          upload_date: '2026-05-03',
          release_date: '2026-05-04',
          provided_by: 'Rightsscale',
          art_track: true,
          length_seconds: 245,
          category: 'Music',
          description_head: ['Provided to YouTube by Rightsscale', '', 'Released on: 2026-05-04', '', 'Auto-generated by YouTube.']
        },
        video.metadata
      )
    end

    test 'metadata keeps all keys present with nil values when the payload has no videoDetails or microformat data' do
      video = Video.new('videoDetails' => {}, 'microformat' => { 'playerMicroformatRenderer' => {} })

      expected_keys = %i[video_id title channel_id channel_name view_count publish_date upload_date
                         release_date provided_by art_track length_seconds category description_head]

      assert_equal expected_keys.sort, video.metadata.keys.sort
      assert_nil video.metadata[:video_id]
      assert_not video.metadata[:art_track]
    end
  end
end
