name: Ruby

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  CI: "true"

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Ruby のセットアップ
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      # 環境変数の設定
      - name: Set environment variables
        run: |
          echo "PG_HOST=localhost" >> $GITHUB_ENV
          echo "PG_USER=postgres" >> $GITHUB_ENV
          echo "PG_PASSWORD=password" >> $GITHUB_ENV
          echo "RAILS_ENV=test" >> $GITHUB_ENV

      - name: Cache vendor/bundle
        uses: actions/cache@v4
        id: cache_gem
        with:
          path: vendor/bundle
          key: v1-gem-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            v1-gem-${{ runner.os }}-

      - name: Build and setup
        run: |
          gem install bundler --no-document -v $(grep "BUNDLED WITH" -1 Gemfile.lock | tail -n 1)
          bundle install --jobs 4 --retry 3

      - name: Database setup
        run: |
          bundle exec rails db:create db:schema:load db:migrate

      - name: Run Rubocop
        run: |
          bundle exec rubocop --parallel

      - name: Run test
        run: |
          bundle exec rails test
